<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AsistenMatakuliah extends Model
{
    use HasFactory;

    protected $table = 'asisten_matakuliah';
    protected $fillable = ['mengajar_id', 'asisten_id'];

    public function mengajar()
    {
        return $this->hasMany(Mengajar::class); // TODO: Change the autogenerated stub
    }

    public function asisten()
    {
        return $this->hasMany(Asisten::class); // TODO: Change the autogenerated stub
    }
}
